name: First Action

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: print env
          run: env | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
        - name: Checkout windows
          uses: actions/checkout@v2
        - name: get env child
          run: "Get-ChildItem Env: | Sort-Object Name"