name: First Action

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: action/checkout@v2
            - name: print env
              uses: env | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Checkout windows
              uses: action/checkout@v2
            - name: get env child
              uses: "Get-ChildItem Env: | Sort-Object Name"